# from app.tools.web import web_search

# print(web_search("Top SaaS companies 2024"))
from app.agent.state import AgentState
from app.agent.executor import execute
from app.agent.writer import write_output

# Example Python code
sample_code = """
public class Calculator {
    public static double divide(double a, double b) {
        return a / ;
    }
}
"""

# Simulate a goal
goal = "Fix bugs, improve robustness, and generate tests"

# Create state
state = AgentState(goal=goal, code=sample_code, language="java")

# Example plan steps (normally generated by planner)
state.plan = [
    "analyze_code: Review the code for bugs and improvements",
    "fix_code: Apply fixes and improvements",
    "generate_tests: Create test cases",
    "optimize_code: Optimize the code for performance"
]

# Execute agent
state = execute(state)

# Write output
output = write_output(state)
print(output)